In [1]:
import numpy as np

In [23]:
A = np.matrix([
    [2, 1],
    [3, 5],
    [5, 7],
    [4, 8]
])

# Matrix B (4x1)
B = np.matrix([
    [6],
    [9],
    [3],
    [1]
])

# Matrix C (4x2)
C = np.matrix([
    [3, 8],
    [8, 6],
    [5, 1],
    [2, 4]
])

In [24]:
A + C

matrix([[ 5,  9],
        [11, 11],
        [10,  8],
        [ 6, 12]])

In [25]:
A-C

matrix([[-1, -7],
        [-5, -1],
        [ 0,  6],
        [ 2,  4]])

In [26]:
B.transpose() @ A

matrix([[58, 80]])

In [27]:
A @ C.transpose()

matrix([[14, 22, 11,  8],
        [49, 54, 20, 26],
        [71, 82, 32, 38],
        [76, 80, 28, 40]])

In [28]:
C.transpose() @ A

matrix([[63, 94],
        [55, 77]])

In [51]:
# Question 3
X = np.matrix([[4],[1],[2],[3],[3],[4]])
Y = np.matrix([[16], [5],[10],[15], [13], [22]])


In [52]:
Y.transpose()@Y

matrix([[1259]])

In [53]:
X.transpose()@X

matrix([[55]])

In [54]:
X.transpose()@Y

matrix([[261]])

In [55]:
# question 4
np.linalg.inv(X.transpose()@X)

matrix([[0.01818182]])

In [57]:
# question 5
X_2 = np.matrix([[8], [4], [0], [-4], [-8]])
Y_2 = np.matrix([[7.8], [9.0], [10.2], [11.0], [11.7]])

In [58]:
Y_2.transpose()@Y_2

matrix([[503.77]])

In [59]:
X_2.transpose()@X_2

matrix([[160]])

In [60]:
X_2.transpose()@Y_2

matrix([[-39.2]])

In [61]:
np.linalg.inv(X_2.transpose()@X_2)

matrix([[0.00625]])

In [64]:
import numpy as np

# Original matrices as shown in Image 2
X_2 = np.matrix([[8], [4], [0], [-4], [-8]])
Y_2 = np.matrix([[7.8], [9.0], [10.2], [11.0], [11.7]])

# Add column of ones for intercept
ones = np.ones((X_2.shape[0], 1))
X_with_ones = np.hstack([ones, X_2])

# a. (1) Vector of estimated regression coefficients
b_hat = np.linalg.inv(X_with_ones.T @ X_with_ones) @ X_with_ones.T @ Y_2
print("\n1. Estimated regression coefficients:")
print(f"b0 (intercept): {b_hat[0,0]:.4f}")
print(f"b1 (slope): {b_hat[1,0]:.4f}")

# a. (2) Vector of residuals
Y_pred = X_with_ones @ b_hat
residuals = Y_2 - Y_pred
print("\n2. Residuals:")
print(residuals)

# a. (3) SSR - Sum of Squares Regression
Y_mean = np.mean(Y_2)
SSR = float(np.sum(np.multiply(Y_pred - Y_mean, Y_pred - Y_mean)))
print(f"\n3. SSR: {SSR:.4f}")

# a. (4) SSE - Sum of Squares Error
SSE = float(np.sum(np.multiply(residuals, residuals)))
print(f"\n4. SSE: {SSE:.4f}")

# a. (5) Estimated variance-covariance matrix of b
MSE = SSE / (X_2.shape[0] - 2)  # n-2 degrees of freedom
var_cov_matrix = MSE * np.linalg.inv(X_with_ones.T @ X_with_ones)
print("\n5. Variance-covariance matrix of b:")
print(var_cov_matrix)

# a. (6) Point estimate of E{Yh} when Xh = -6
X_h = np.matrix([[1, -6]])  # Design vector for Xh = -6
E_Y_h = (X_h @ b_hat)[0, 0]  # Extract single element
print(f"\n6. E(Yh) when Xh = -6: {E_Y_h:.4f}")

# a. (7) Estimated variance of Yh when Xh = -6
var_Y_h = MSE * float((X_h @ np.linalg.inv(X_with_ones.T @ X_with_ones) @ X_h.T)[0, 0])
print(f"\n7. Var(Yh) when Xh = -6: {var_Y_h:.4f}")

# c. Hat matrix H
H = X_with_ones @ np.linalg.inv(X_with_ones.T @ X_with_ones) @ X_with_ones.T
print("\nc. Hat matrix H:")
print(H)

# d. s^2{e}
s2_e = SSE / (X_2.shape[0] - 2)  # Same as MSE calculated earlier
print(f"\nd. s^2(e): {s2_e:.4f}")


1. Estimated regression coefficients:
b0 (intercept): 9.9400
b1 (slope): -0.2450

2. Residuals:
[[-0.18]
 [ 0.04]
 [ 0.26]
 [ 0.08]
 [-0.2 ]]

3. SSR: 9.6040

4. SSE: 0.1480

5. Variance-covariance matrix of b:
[[0.00986667 0.        ]
 [0.         0.00030833]]

6. E(Yh) when Xh = -6: 11.4100

7. Var(Yh) when Xh = -6: 0.0210

c. Hat matrix H:
[[ 0.6  0.4  0.2  0.  -0.2]
 [ 0.4  0.3  0.2  0.1  0. ]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.   0.1  0.2  0.3  0.4]
 [-0.2  0.   0.2  0.4  0.6]]

d. s^2(e): 0.0493
